### ISSUE TITLE
undefine SSD1306_128_32

### ISSUE THREAD

**Issue by mcauser** [adafruit/Adafruit_SSD1306#57]
Currently when I want to use this library with a 128x64 OLED, I need to edit the `Adafruit_SSD1306.h` and comment out `#define SSD1306_128_32`.

Would a better pattern be to not define it in the library and rely on a `#define` in the code using the library?

**Comment by Twilight** [comment]
+1

**Comment by fpapadopou** [comment]
Hey @tdicola, this is Fotis from [codebender](https://codebender.cc). We just added the SSD1306 library to our platform and we've bumped into the same issue. Users have no write access to libraries' files on codebender, so we'd appreciate if you could move the _defines_ to the examples's code, instead of them being hardcoded in the library code.

Thanks in advance!

**Comment by Anton-V-K** [comment]
Modifying library code when building sketches for different schematics is a pain in the neck.
Could you please adjust the source code in the way which would allow developers to define constants in their code.
Here is an example how this can be achieved in `Adafruit_SSD1306.h`: 
`
#ifndef SSD1306_I2C_ADDRESS
#define SSD1306_I2C_ADDRESS   0x3C
#endif
#if !defined(SSD1306_128_64) && !defined(SSD1306_128_32) && !defined(SSD1306_96_16)
#define SSD1306_128_32
#endif
`
This way you'll keep backward compatibility.

**Comment by ladyada** [comment]
oh weird, the arduino editor changed - this wasnt possible before due to the way compiling work but apparently it does now?

**Comment by alexgorbatchev** [comment]
how much work would it be to address this?

**Comment by ladyada** [comment]
someone would have to redo the library to use malloc - feel free to do it and send a PR!

**Comment by programus** [comment]
redo the library to use malloc is a big work. So I think you can adopt the option from @Anton-V-K before anyone send a perfect malloc PR. 
At least, @Anton-V-K 's version allows me to set the resolution by the build flag `-D SSD1306_128_64`. I could specify a build flag when I use some IDE like platformio instead of the default Arduino IDE.
But current version, I can do nothing if I want to keep the library as is.

**Comment by ladyada** [comment]
anton's solution doesnt work in Arduino, as how C++ handles #defines, they're not global :) we would only accept a PR that works in Arduino since it is how people use the library

**Comment by programus** [comment]
I tried to work out a malloc solution, but it seems the memory are not big enough to support it. So I worked out another solution that separates header files and implementations for each resolution but keep the core source being reused. 
This might not be the best solution, but it could avoid changing the source of the library when changing the OLED resolution.

**Comment by alexgorbatchev** [comment]
@programus i like this, would you submit a PR for review?

**Comment by programus** [comment]
@alexgorbatchev I have submitted a PR https://github.com/adafruit/Adafruit_SSD1306/pull/94

**Comment by harbaum** [comment]
This sounds great, please accept this.

**Comment by ladyada** [comment]
hiya, we would accept a solution with malloc that is backward compatible with current code, not #include noodling :)

**Comment by programus** [comment]
I also tried the malloc solution but it seems consume too much memory to let arduino do something else besides display. So I have to work out this #include noodling thing.

**Comment by PaintYourDragon** [comment]
Fixed as of v1.2; display buffer uses malloc.
